Solutions for file exercises 1&2
bregman-arie/python-exercises pull request #6
Opened 2022-06-21 07:56 UTC by ayodele-ademeso

I added the solutions for the first two exercises for "Files" in the solutions directory.

2022-06-21 08:53 UTC, bregman-arie requested changes

2022-06-21 08:53 UTC, bregman-arie commented on solutions/files/read_a_file.md
> +    print (content)
space between print and "(content)"

2022-06-21 09:09 UTC, ayodele-ademeso commented on solutions/files/read_a_file.md
> +    print (content)
This has been fixed

2022-06-22 08:50 UTC, bregman-arie approved these changes

2022-06-22 08:50 UTC, merged